### ISSUE TITLE
No exist container for transformer

### ISSUE THREAD

**Issue by hmkim** [aws-samples/drug-discovery-workflows#12]
This code use the transformers image in ECR. But I can't found the container information in this repository.

https://github.com/aws-samples/drug-discovery-workflows/blob/f3601c21664dab5691c046077cecba21918dd946/workflows/esmfold/main.wdl#L21

I just want to make sure I'm not missing something, thank you.

**Comment by brianloyal** [comment]
Good catch! Fixed in 0c0b0dc71f16daf8bfd8aed7cceadb793c369340
